export EMI_RELEASE_REMOTE_RPM="http://emisoft.web.cern.ch/emisoft/dist/EMI/2/sl6/x86_64/base/emi-release-2.0.0-1.sl6.noarch.rpm"
export EPEL_RELEASE_REMOTE_RPM="http://www.nic.funet.fi/pub/mirrors/fedora.redhat.com/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm"
export YAIM_CONFIGURATION_FILE="https://raw.github.com/italiangrid/storm-deployment-test/master/siteinfo/emi2-storm.def"
export JAVA_LOCATION="/usr/lib/jvm/java"
export ENABLE_GRIDHTTPS_SERVER="false"
