export ADDITIONAL_REPO="http://radiohead.cnaf.infn.it:9999/view/REPOS/job/repo_storm_develop_SL5/lastSuccessfulBuild/artifact/storm_develop_sl5.repo"
export EMI_RELEASE_REMOTE_RPM="http://emisoft.web.cern.ch/emisoft/dist/EMI/3/sl5/x86_64/base/emi-release-3.0.0-2.el5.noarch.rpm"
export EPEL_RELEASE_REMOTE_RPM="http://archives.fedoraproject.org/pub/epel/5/x86_64/epel-release-5-4.noarch.rpm"
export JAVA_LOCATION="/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.0.x86_64/jre"
export ENABLE_GRIDHTTPS_SERVER="true"
