export EMI_RELEASE_RPM="http://emisoft.web.cern.ch/emisoft/dist/EMI/3/sl5/x86_64/base/$emi_release.el5.noarch.rpm"
export EPEL_RELEASE_RPM="http://archives.fedoraproject.org/pub/epel/5/x86_64/epel-release-5-4.noarch.rpm"
export EGI_TRUSTANCHORS_REPO="http://repository.egi.eu/sw/production/cas/1/current/repo-files/EGI-trustanchors.repo"
export IGI_TEST_CA_REPO="http://radiohead.cnaf.infn.it:9999/view/REPOS/job/repo_test_ca/lastSuccessfulBuild/artifact/test-ca.repo"
export ROBOT_FRAMEWORK_VERSION="2.8.1"